### ISSUE TITLE
ability to customize vip,service group and server names.

### ISSUE THREAD

**Issue by warroyo** [citrix/citrix-k8s-ingress-controller#245] opened 2020-05-29 16:09 UTC
is there currently the ability to change the naming convention for the objects created in the ADC or be able to specify a static name using an annotation? 

I have looked at smart annotations but can't find a list of what is available for these

**Comment by verzunof** [comment] 2020-05-29 21:42
@warroyo No, there is no ability to change entity naming. All those names are auto generated based on resources that they represent, apart from cert keys that are cryptic due to ADC technical issues.
Some names may not fit into names length ADC restrictions, this is being worked on.

**Comment by warroyo** [comment] 2020-06-22 15:02
thanks @verzunof feel free to close this or keep it open until there is a fix

**Comment by ankits123** [comment] 2021-09-22 05:53
closing the issue as this is expected behavior.

**Closed** 2021-09-22 05:53 UTC
