### ISSUE TITLE
IPAM / Ingress Controller keep deleting each others VIPs causing service disruptions

### ISSUE THREAD

**Issue by lhw** [citrix/citrix-k8s-ingress-controller#409] opened 2021-05-11 14:00 UTC
**Describe the bug**
An address allocated for a loadbalancer will be created and deleted dozens of times a second by the interaction between the ipam and ingress controller

**To Reproduce**
1. Add service with loadbalancer type
2. Wait for provisioning
3. Chaos ensues

**Expected behavior**
- Not spam millions of lines of log and commands.
- Configure IP address.

And I almost consider the last point optional at this point

**Logs**
kubectl logs: https://gist.github.com/lhw/76ef70823251bea2db202d51de951f07

Kubernetes service:
```
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     41s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     41s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     41s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     41s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     43s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     43s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     43s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     43s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     44s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     44s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     44s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     44s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     46s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     46s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     46s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     46s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     47s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     47s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     47s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     47s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     49s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     49s
```

**Additional context**

```yaml
# helm values cic chart
adcCredentialSecret: netscaler-login
crds:
  install: true
  retainOnDelete: true
defaultSSLCertSecret: pki-default-certificate
entityPrefix: stg
exporter:
  required: false
image: quay.io/citrix/citrix-k8s-ingress-controller:1.13.15
ingressClass:
- intern
ipam: true
license:
  accept: "yes"
logLevel: info
nodeSelector:
  key: node-role.kubernetes.io/master
  value: ""
nodeWatch: false
nsHTTP2ServerSide: "ON"
nsIP: 172.31.102.23
nsProtocol: https
nsVIP: 172.31.203.22
podIPsforServiceGroupMembers: true
serviceClass:
- intern
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Equal
updateIngressStatus: true
```

**Comment by apoorva-05** [comment] 2021-05-12 12:39
@lhw We are trying to reproduce and find the root cause the issue. We will get back to you on this.

**Comment by apoorva-05** [comment] 2021-05-20 06:27
@lhw unfortunately we were not able to reproduce this issue. We would want some more details about this issue from you. 
1. Is it possible for you to share the IPAM logs during this duration.
2. Is this the complete CIC log during the given timeframe or is it filtered?
3. If you still have the VIP CRD resource in your cluster can that be shared. 
    ````
    kubectl get vip --all-namespaces
``

**Comment by lhw** [comment] 2021-05-25 09:59
I recreated the issue for you:
> 1. Is it possible for you to share the IPAM logs during this duration.

Here the complete log for the time period: https://gist.github.com/lhw/3e998cda187c17ce8bd08ef3ebf1e09d under cic.log. Luckily only around 1900 lines for the minute.

> 2. Is this the complete CIC log during the given timeframe or is it filtered?

It wasn't filtered. The gist link also includes the cic-ipam.log

>  3. If you still have the VIP CRD resource in your cluster can that be shared.

The gist link also contains the vip yaml that i was able to grasp before it was deleted again.

**Comment by apoorva-05** [comment] 2021-05-25 11:39
@lhw is it possible to provide the type loadbalancer service definition too?

**Comment by apoorva-05** [comment] 2021-05-25 11:53
@lhw Just clarifying a few things:
1. Is there only one instance of Citrix Ingress Controller and IPAM running in the cluster?
2. Highly unlikely, but is there a daemon process or workload monitor which might be deleting the VIP resources created by the ingress controller in the kube-system namespace?

**Comment by lhw** [comment] 2021-05-25 12:07
>     1. Is there only one instance of Citrix Ingress Controller and IPAM running in the cluster?

The issue is present on two clusters. But all clusters we have do have more than one ingress controller. The one from the log has three: The helm values for all three are here: https://gist.github.com/lhw/5a2c52260620ef6f4106b4a7f75417cb each has its own service-class though.

>     2. Highly unlikely, but is there a daemon process or workload monitor which might be deleting the VIP resources created by the ingress controller in the kube-system namespace?

Only cic roles have access to the vips. So nothing else can touch the resource. But no. There is no additional tool interacting with it.

**Comment by lhw** [comment] 2021-05-25 12:14
As you were pointing out the other cics. Here is the log of the other CICs from the same time period. https://gist.github.com/lhw/7b9f2e2a2b0992317c1f37155060f9e4

They seem to be reacting to the service even though the service class does not match their supplied value.

**Comment by lhw** [comment] 2021-05-25 12:57
After disabling the ipam feature on both the `extern` and `extern-fbt` cics it works now. So it looks like the cics seem to be ignoring the service-class.

**Comment by apoorva-05** [comment] 2021-05-25 13:01
@lhw Thanks a lot for all the information. we know the root cause now. This will be fixed in the next release.

**Closed as completed** 2021-06-17 13:53 UTC
